<?php
error_reporting(0);

$randomizequestions ="yes";
$a = array(
1 => array(
   read => "<b> Question 1-10</b><br>
   Europe is the smallest of planet Jupiter's four largest moons and the second moon out from Jupiter. Until 1979, it was just another astronomy textbook statistic. Then came the close-up images obtained by the exploratory spacecraft Voyager 2, and within days, Europe was transformed--in our perception, at least--into one of the solar system's most intriguing worlds. The biggest initial surprise was the almost total lack of detail, especially from far away. Even at close range, the only visible features are thin, kinked brown lines resembling cracks in an eggshell. And this analogy is not far off the mark.
   <br><br>
   The surface of Europe is almost pure water ice, but a nearly complete absence of craters indicates that Europe's surface ice resembles Earth's Antarctic ice cap. The eggshell analogy may be quite accurate since the ice could be as little as a few kilometers thick--a tree shell around what is likely a subsurface liquid ocean that, in turn, encases a rocky core. The interior of Europe has been kept warm over the cons by tidal forces generated by the varying gravitational tugs of the other big moons as they wheel around Jupiter. The tides on Europe pull and relax in an endless cycle. The resulting internal heat keeps what would otherwise be ice melted almost to the surface. The cracklike marks on Europe's icy face appear to be fractures where water or slush oozes from below.
   <br><br>
   Soon after Voyager 2's encounter with Jupiter in 1979, when the best images of Europe were obtained, researchers advanced the startling idea that Europe's subsurface ocean might harbor life. Life processes could have begun when Jupiter was releasing a vast store of internal heat. Jupiter's early heat was produced by the compression of the material forming the giant planet. Just as the Sun is far less radiant today than the primal Sun, so the internal heat generated by Jupiter is minor compared to its former intensity. During this warm phase, some 4.6 billion years ago, Europe's ocean may have been liquid right to the surface, making it a crucible for life.",
   0 => "What does the passage mainly discuss?",
   1 => "A) The effect of the tides on Europe's interior",
   2 => "B) Temperature variations on Jupiter's moons",
   3 => "C) Discoveries leading to a theory about one of Jupiter's moons",
   4 => "D) Techniques used by Voyager 2 to obtain close-up images",
   5 => "Jawab: C. Skill: Main Idea Question (Pertanyaan Ide Pokok) <br>
   Cara menjawab ide pokok ialah dengan melihat kalimat pertama setiap paragraf.",
   6 => 3
),
2 => array(
   read => "<b> Question 1-10</b><br>
   Europe is the smallest of planet Jupiter's four largest moons and the second moon out from Jupiter. Until 1979, it was just another astronomy textbook statistic. Then came the close-up images obtained by the exploratory spacecraft Voyager 2, and within days, Europe was transformed--in our perception, at least--into one of the solar system's most intriguing worlds. The biggest initial surprise was the almost total lack of detail, especially from far away. Even at close range, the only visible features are thin, kinked brown lines resembling cracks in an eggshell. And this analogy is not far off the mark.
   <br><br>
   The surface of Europe is almost pure water ice, but a nearly complete absence of craters indicates that Europe's surface ice resembles Earth's Antarctic ice cap. The eggshell analogy may be quite accurate since the ice could be as little as a few kilometers thick--a tree shell around what is likely a subsurface liquid ocean that, in turn, encases a rocky core. The interior of Europe has been kept warm over the cons by tidal forces generated by the varying gravitational tugs of the other big moons as they wheel around Jupiter. The tides on Europe pull and relax in an endless cycle. The resulting internal heat keeps what would otherwise be ice melted almost to the surface. The cracklike marks on Europe's icy face appear to be fractures where water or slush oozes from below.
   <br><br>
   Soon after Voyager 2's encounter with Jupiter in 1979, when the best images of Europe were obtained, researchers advanced the startling idea that Europe's subsurface ocean might harbor life. Life processes could have begun when Jupiter was releasing a vast store of internal heat. Jupiter's early heat was produced by the compression of the material forming the giant planet. Just as the Sun is far less radiant today than the primal Sun, so the internal heat generated by Jupiter is minor compared to its former intensity. During this warm phase, some 4.6 billion years ago, Europe's ocean may have been liquid right to the surface, making it a crucible for life.",
   0 => "The word 'intriguing' in line 5 is closest in meaning to",
   1 => "A) changing",
   2 => "B) perfect",
   3 => "C) visible",
   4 => "D) fascinating",
   5 => "Jawab: D. Skill: Vocabulary Question (Pertanyaan tentang pemahaman kosakata). Cara menjawab soal kosakata ialah dengan menyesuaikan konteks makna kalimat dari kosakata yang ditanyakan.",
   6 => 4
),
3 => array(
   read => "<b> Question 1-10</b><br>
   Europe is the smallest of planet Jupiter's four largest moons and the second moon out from Jupiter. Until 1979, it was just another astronomy textbook statistic. Then came the close-up images obtained by the exploratory spacecraft Voyager 2, and within days, Europe was transformed--in our perception, at least--into one of the solar system's most intriguing worlds. The biggest initial surprise was the almost total lack of detail, especially from far away. Even at close range, the only visible features are thin, kinked brown lines resembling cracks in an eggshell. And this analogy is not far off the mark.
   <br><br>
   The surface of Europe is almost pure water ice, but a nearly complete absence of craters indicates that Europe's surface ice resembles Earth's Antarctic ice cap. The eggshell analogy may be quite accurate since the ice could be as little as a few kilometers thick--a tree shell around what is likely a subsurface liquid ocean that, in turn, encases a rocky core. The interior of Europe has been kept warm over the cons by tidal forces generated by the varying gravitational tugs of the other big moons as they wheel around Jupiter. The tides on Europe pull and relax in an endless cycle. The resulting internal heat keeps what would otherwise be ice melted almost to the surface. The cracklike marks on Europe's icy face appear to be fractures where water or slush oozes from below.
   <br><br>
   Soon after Voyager 2's encounter with Jupiter in 1979, when the best images of Europe were obtained, researchers advanced the startling idea that Europe's subsurface ocean might harbor life. Life processes could have begun when Jupiter was releasing a vast store of internal heat. Jupiter's early heat was produced by the compression of the material forming the giant planet. Just as the Sun is far less radiant today than the primal Sun, so the internal heat generated by Jupiter is minor compared to its former intensity. During this warm phase, some 4.6 billion years ago, Europe's ocean may have been liquid right to the surface, making it a crucible for life.",
   0 => "In line 7, the author mentions 'cracks in an eggshell' in order to help readers?",
   1 => "A) visualize Europe as scientists saw it in the Voyager 2 images",
   2 => "B) appreciate the extensive and detailed information available by viewing Europe from far away",
   3 => "C) understand the relationship of Europe to the solar system",
   4 => "D) recognize the similarity of Europe to Jupiter's other moons",
   5 => "Jawab: A. Cara menjawab soal seperti ini ialah dengan memahami kalimat di mana phrase tersebut dan kalimat-kalimat sebelumnya. <br>
   Then came the close-up images obtained by the exploratory spacecraft Voyager 2, and within days, Europe was transformed--in our perception, at least--into one of the solar system's most intriguing worlds. The biggest initial surprise was the almost total lack of detail, especially from far away. Even at close range, the only visible features are thin, kinked brown lines resembling cracks in an eggshell.",
   6 => 1
),
4 => array(
   read => "<b> Question 1-10</b><br>
   Europe is the smallest of planet Jupiter's four largest moons and the second moon out from Jupiter. Until 1979, it was just another astronomy textbook statistic. Then came the close-up images obtained by the exploratory spacecraft Voyager 2, and within days, Europe was transformed--in our perception, at least--into one of the solar system's most intriguing worlds. The biggest initial surprise was the almost total lack of detail, especially from far away. Even at close range, the only visible features are thin, kinked brown lines resembling cracks in an eggshell. And this analogy is not far off the mark.
   <br><br>
   The surface of Europe is almost pure water ice, but a nearly complete absence of craters indicates that Europe's surface ice resembles Earth's Antarctic ice cap. The eggshell analogy may be quite accurate since the ice could be as little as a few kilometers thick--a tree shell around what is likely a subsurface liquid ocean that, in turn, encases a rocky core. The interior of Europe has been kept warm over the cons by tidal forces generated by the varying gravitational tugs of the other big moons as they wheel around Jupiter. The tides on Europe pull and relax in an endless cycle. The resulting internal heat keeps what would otherwise be ice melted almost to the surface. The cracklike marks on Europe's icy face appear to be fractures where water or slush oozes from below.
   <br><br>
   Soon after Voyager 2's encounter with Jupiter in 1979, when the best images of Europe were obtained, researchers advanced the startling idea that Europe's subsurface ocean might harbor life. Life processes could have begun when Jupiter was releasing a vast store of internal heat. Jupiter's early heat was produced by the compression of the material forming the giant planet. Just as the Sun is far less radiant today than the primal Sun, so the internal heat generated by Jupiter is minor compared to its former intensity. During this warm phase, some 4.6 billion years ago, Europe's ocean may have been liquid right to the surface, making it a crucible for life.",
   0 => "It can be inferred from the passage that astronomy textbooks prior to 1979?",
   1 => "A) provided many contradictory statistics about Europe",
   2 => "B) considered Europe the most important of Jupiter's moons",
   3 => "C) did not emphasize Europe because little information of interest was available",
   4 => "D) did not mention Europe because it had not yet been discovered",
   5 => "Jawab: C. Jawaban terdapat pada sebagian besar paragraf pertama.<br>
   Europe is the smallest of planet Jupiter's four largest moons and the second moon out from Jupiter. Until 1979, it was just another astronomy textbook statistic. Then came the close-up images obtained by the exploratory spacecraft Voyager 2, and within days, Europe was transformed--in our perception, at least--into one of the solar system's most intriguing worlds. The biggest initial surprise was the almost total lack of detail, especially from far away. ",
   6 => 3
),
5 => array(
   read => "<b> Question 1-10</b><br>
   Europe is the smallest of planet Jupiter's four largest moons and the second moon out from Jupiter. Until 1979, it was just another astronomy textbook statistic. Then came the close-up images obtained by the exploratory spacecraft Voyager 2, and within days, Europe was transformed--in our perception, at least--into one of the solar system's most intriguing worlds. The biggest initial surprise was the almost total lack of detail, especially from far away. Even at close range, the only visible features are thin, kinked brown lines resembling cracks in an eggshell. And this analogy is not far off the mark.
   <br><br>
   The surface of Europe is almost pure water ice, but a nearly complete absence of craters indicates that Europe's surface ice resembles Earth's Antarctic ice cap. The eggshell analogy may be quite accurate since the ice could be as little as a few kilometers thick--a tree shell around what is likely a subsurface liquid ocean that, in turn, encases a rocky core. The interior of Europe has been kept warm over the cons by tidal forces generated by the varying gravitational tugs of the other big moons as they wheel around Jupiter. The tides on Europe pull and relax in an endless cycle. The resulting internal heat keeps what would otherwise be ice melted almost to the surface. The cracklike marks on Europe's icy face appear to be fractures where water or slush oozes from below.
   <br><br>
   Soon after Voyager 2's encounter with Jupiter in 1979, when the best images of Europe were obtained, researchers advanced the startling idea that Europe's subsurface ocean might harbor life. Life processes could have begun when Jupiter was releasing a vast store of internal heat. Jupiter's early heat was produced by the compression of the material forming the giant planet. Just as the Sun is far less radiant today than the primal Sun, so the internal heat generated by Jupiter is minor compared to its former intensity. During this warm phase, some 4.6 billion years ago, Europe's ocean may have been liquid right to the surface, making it a crucible for life.",
   0 => "What does the author mean by stating in line 7 that 'this analogy is not far off the mark'?",
   1 => "A) The definition is not precise.",
   2 => "B) The discussion lacks necessary information.",
   3 => "C) The differences are probably significant.",
   4 => "D) The comparison is quite appropriate.",
   5 => "Jawab: D. Pahami kalimat dari phrase dan kalimat-kalimat sebelumnya.<br>
   Even at close range, the only visible features are thin, kinked brown lines resembling cracks in an eggshell. And this analogy is not far off the mark.",
   6 => 4
),
6 => array(
   read => "<b> Question 1-10</b><br>
   Europe is the smallest of planet Jupiter's four largest moons and the second moon out from Jupiter. Until 1979, it was just another astronomy textbook statistic. Then came the close-up images obtained by the exploratory spacecraft Voyager 2, and within days, Europe was transformed--in our perception, at least--into one of the solar system's most intriguing worlds. The biggest initial surprise was the almost total lack of detail, especially from far away. Even at close range, the only visible features are thin, kinked brown lines resembling cracks in an eggshell. And this analogy is not far off the mark.
   <br><br>
   The surface of Europe is almost pure water ice, but a nearly complete absence of craters indicates that Europe's surface ice resembles Earth's Antarctic ice cap. The eggshell analogy may be quite accurate since the ice could be as little as a few kilometers thick--a tree shell around what is likely a subsurface liquid ocean that, in turn, encases a rocky core. The interior of Europe has been kept warm over the cons by tidal forces generated by the varying gravitational tugs of the other big moons as they wheel around Jupiter. The tides on Europe pull and relax in an endless cycle. The resulting internal heat keeps what would otherwise be ice melted almost to the surface. The cracklike marks on Europe's icy face appear to be fractures where water or slush oozes from below.
   <br><br>
   Soon after Voyager 2's encounter with Jupiter in 1979, when the best images of Europe were obtained, researchers advanced the startling idea that Europe's subsurface ocean might harbor life. Life processes could have begun when Jupiter was releasing a vast store of internal heat. Jupiter's early heat was produced by the compression of the material forming the giant planet. Just as the Sun is far less radiant today than the primal Sun, so the internal heat generated by Jupiter is minor compared to its former intensity. During this warm phase, some 4.6 billion years ago, Europe's ocean may have been liquid right to the surface, making it a crucible for life.",
   0 => "It can be inferred from the passage that Europe and Antarctica have in common which of the following?",
   1 => "A) Both appear to have a surface with many craters.",
   2 => "B) Both may have water beneath a thin, hard surface.",
   3 => "C) Both have an ice cap that is melting rapidly.",
   4 => "D) Both have areas encased by a rocky exterior.",
   5 => "Jawab: B. Complete absence (betul-betul tidak ada)<br>
   The surface of Europe is almost pure water ice, but a nearly complete absence of craters indicates that Europe's surface ice resembles Earth's Antarctic ice cap.",
   6 => 2
),
7 => array(
   read => "<b> Question 1-10</b><br>
   Europe is the smallest of planet Jupiter's four largest moons and the second moon out from Jupiter. Until 1979, it was just another astronomy textbook statistic. Then came the close-up images obtained by the exploratory spacecraft Voyager 2, and within days, Europe was transformed--in our perception, at least--into one of the solar system's most intriguing worlds. The biggest initial surprise was the almost total lack of detail, especially from far away. Even at close range, the only visible features are thin, kinked brown lines resembling cracks in an eggshell. And this analogy is not far off the mark.
   <br><br>
   The surface of Europe is almost pure water ice, but a nearly complete absence of craters indicates that Europe's surface ice resembles Earth's Antarctic ice cap. The eggshell analogy may be quite accurate since the ice could be as little as a few kilometers thick--a tree shell around what is likely a subsurface liquid ocean that, in turn, encases a rocky core. The interior of Europe has been kept warm over the cons by tidal forces generated by the varying gravitational tugs of the other big moons as they wheel around Jupiter. The tides on Europe pull and relax in an endless cycle. The resulting internal heat keeps what would otherwise be ice melted almost to the surface. The cracklike marks on Europe's icy face appear to be fractures where water or slush oozes from below.
   <br><br>
   Soon after Voyager 2's encounter with Jupiter in 1979, when the best images of Europe were obtained, researchers advanced the startling idea that Europe's subsurface ocean might harbor life. Life processes could have begun when Jupiter was releasing a vast store of internal heat. Jupiter's early heat was produced by the compression of the material forming the giant planet. Just as the Sun is far less radiant today than the primal Sun, so the internal heat generated by Jupiter is minor compared to its former intensity. During this warm phase, some 4.6 billion years ago, Europe's ocean may have been liquid right to the surface, making it a crucible for life.",
   0 => "The word 'endless' in line 14 is closest in meaning to",
   1 => "A) new",
   2 => "B) final",
   3 => "C) temporary",
   4 => "D) continuous",
   5 => "Jawab: D. endless (tak berujung) = continuous (berkelanjutan).",
   6 => 4
),
8 => array(
   read => "<b> Question 1-10</b><br>
   Europe is the smallest of planet Jupiter's four largest moons and the second moon out from Jupiter. Until 1979, it was just another astronomy textbook statistic. Then came the close-up images obtained by the exploratory spacecraft Voyager 2, and within days, Europe was transformed--in our perception, at least--into one of the solar system's most intriguing worlds. The biggest initial surprise was the almost total lack of detail, especially from far away. Even at close range, the only visible features are thin, kinked brown lines resembling cracks in an eggshell. And this analogy is not far off the mark.
   <br><br>
   The surface of Europe is almost pure water ice, but a nearly complete absence of craters indicates that Europe's surface ice resembles Earth's Antarctic ice cap. The eggshell analogy may be quite accurate since the ice could be as little as a few kilometers thick--a tree shell around what is likely a subsurface liquid ocean that, in turn, encases a rocky core. The interior of Europe has been kept warm over the cons by tidal forces generated by the varying gravitational tugs of the other big moons as they wheel around Jupiter. The tides on Europe pull and relax in an endless cycle. The resulting internal heat keeps what would otherwise be ice melted almost to the surface. The cracklike marks on Europe's icy face appear to be fractures where water or slush oozes from below.
   <br><br>
   Soon after Voyager 2's encounter with Jupiter in 1979, when the best images of Europe were obtained, researchers advanced the startling idea that Europe's subsurface ocean might harbor life. Life processes could have begun when Jupiter was releasing a vast store of internal heat. Jupiter's early heat was produced by the compression of the material forming the giant planet. Just as the Sun is far less radiant today than the primal Sun, so the internal heat generated by Jupiter is minor compared to its former intensity. During this warm phase, some 4.6 billion years ago, Europe's ocean may have been liquid right to the surface, making it a crucible for life.",
   0 => "According to the passage, what is the effect of Jupiter's other large moons on Europe?",
   1 => "A) They prevent Europe's subsurface waters from freezing.",
   2 => "B) They prevent tides that could damage Europe's surface.",
   3 => "C) They produce the very hard layer of ice that characterizes Europe.",
   4 => "D) They assure that the gravitational pull on Europe is maintained at a steady level.",
   5 => "Jawab: A. Jawaban terdapat pada kalimat Jupiter's early heat was produced by the compression of the material forming the giant planet.",
   6 => 1
),
9 => array(
   read => "<b> Question 1-10</b><br>
   Europe is the smallest of planet Jupiter's four largest moons and the second moon out from Jupiter. Until 1979, it was just another astronomy textbook statistic. Then came the close-up images obtained by the exploratory spacecraft Voyager 2, and within days, Europe was transformed--in our perception, at least--into one of the solar system's most intriguing worlds. The biggest initial surprise was the almost total lack of detail, especially from far away. Even at close range, the only visible features are thin, kinked brown lines resembling cracks in an eggshell. And this analogy is not far off the mark.
   <br><br>
   The surface of Europe is almost pure water ice, but a nearly complete absence of craters indicates that Europe's surface ice resembles Earth's Antarctic ice cap. The eggshell analogy may be quite accurate since the ice could be as little as a few kilometers thick--a tree shell around what is likely a subsurface liquid ocean that, in turn, encases a rocky core. The interior of Europe has been kept warm over the cons by tidal forces generated by the varying gravitational tugs of the other big moons as they wheel around Jupiter. The tides on Europe pull and relax in an endless cycle. The resulting internal heat keeps what would otherwise be ice melted almost to the surface. The cracklike marks on Europe's icy face appear to be fractures where water or slush oozes from below.
   <br><br>
   Soon after Voyager 2's encounter with Jupiter in 1979, when the best images of Europe were obtained, researchers advanced the startling idea that Europe's subsurface ocean might harbor life. Life processes could have begun when Jupiter was releasing a vast store of internal heat. Jupiter's early heat was produced by the compression of the material forming the giant planet. Just as the Sun is far less radiant today than the primal Sun, so the internal heat generated by Jupiter is minor compared to its former intensity. During this warm phase, some 4.6 billion years ago, Europe's ocean may have been liquid right to the surface, making it a crucible for life.",
   0 => "According to the passage, what is believed to cause the thin lines seen on Europa’s surface?",
   1 => "A) A long period of extremely high tides",
   2 => "B) Water breaking through from beneath the surface ice ",
   3 => "C) The continuous pressure of slush on top of the ice",
   4 => "D) Heat generated by the hot rocky core ",
   5 => "Jawab: B. ",
   6 => 2
),
);

$max=9;

$question=$_POST["question"] ;

if ($_POST["Randon"]==0){
        if($randomizequestions =="yes"){$randval = 1;}else{$randval=1;}
        $randval2 = $randval;
        }else{
        $randval=$_POST["Randon"];
        $randval2=$_POST["Randon"] + $question;
                if ($randval2>$max){
                $randval2=$randval2-$max;
                }
        }
        
$ok=$_POST["ok"] ;

if ($question==0){
        $question=0;
        $ok=0;
        $percentaje=0;
        }else{
        $percentaje= Round(100*$ok / $question);
        }
?>


<!DOCTYPE html>
<html lang="en">
<head>
<title>TOEFL Online</title>
<meta charset="utf-8">
<link rel="icon" href="">
<link rel="shortcut icon" href="images/favicon.png">
<link rel="stylesheet" href="css/style.css">

<script language='JavaScript'>
<!-- 
function Goahead (number){
        if (document.percentaje.response.value==0){
                if (number==<?php print $a[$randval2][6] ; ?>){
                        document.percentaje.response.value=1
                        document.percentaje.question.value++
                        document.percentaje.ok.value++
                }else{
                        document.percentaje.response.value=1
                        document.percentaje.question.value++
                }
        }
        if (number==<?php print $a[$randval2][6] ; ?>){
                document.question.response.value="Correct"
        }else{
                document.question.response.value="Incorrect"
        }
}
// -->
</script>

</head>
<body>
  <script type="text/javascript">
     var showListForm = function() {
        document.getElementById("penjelasan-form").setAttribute("style", "display:none");
        document.getElementById("show-form").setAttribute("style", "display:block");
        document.getElementById("hide-form").setAttribute("style", "display:none");
      }
    </script>
    <script type="text/javascript">
     var showPenjelasanForm = function() {
        document.getElementById("penjelasan-form").setAttribute("style", "display:block");
        document.getElementById("show-form").setAttribute("style", "display:none");
        document.getElementById("hide-form").setAttribute("style", "display:block");
      }
    </script>

<!--Start Header-->
<header class="page1">
  <div class="container_12">
    <div class="grid_12">
      <h1><a href="#" onClick="goToByScroll('page1'); return false;"><img height="30px" width="1300px" src="images/logo2.png" alt=""></a></h1>
        <div class="menu_block">
        <nav class="">
          <ul class="sf-menu">
            <li class="men1"><a onClick="goToByScroll('page1'); return false;" href="index.html">Home</a><strong class="hover"></strong></li>
          </ul>
        </nav>
      </div>
    </div>
  </div>
</header>
<!--End Header-->

<!-- Start Grammar -->
<div id="page2" class="content"> 
  <div class="container_12">\
  <div class="grid_14">
    <div class="box" style="margin-top:-30px; width:1000px; margin-left:-30px;">
      <div style="color:#666666; font-size:30px; padding-bottom:30px; ">Structure - Model Test 1
      </div>
         <div style="background-color:#666666; color:white; margin-left:10px; width:980px; padding:5px 0">There are 9 questions in this quiz. Read the reading explanation below. 
          <div class="box3">
             <p align="right">Percentage of correct answer: <?php print $percentaje; ?> %</p>
             <hr>
            <table id="t01" border="0" cellspacing="5px" width="950px">
              <?php if ($question<$max){ ?>
              <tr><td>
              <form method="POST" name="percentaje" action="<?php print $URL; ?>">
                <input type="hidden" name="response" value=0>
                <input type="hidden" name="question" value=<?php print $question; ?>>
                <input type="hidden" name="ok" value=<?php print $ok; ?>>
                <input type="hidden" name="Randon" value=<?php print $randval; ?>>
                <input style="font-family:Trebuchet ms; font-size:14.5px; width:80px; border:1px; margin-left:860px;" type="submit" value="Next">
              </form>
              </td></tr>

              <tr width="500px">
                <td><p style="margin-right:330px;"><?php print $a[$randval2][read]; ?></p></td>
                <td>
              <form method="POST" name="question" action="" style="padding-left:-150px; margin-left:-300px; padding-right:10px;">
              <div >
              <br><strong><?php print $question+1; ?>. </strong><?php print "<b>".$a[$randval2][0]."</b>"; ?>
                <br><br><input type="radio" name="option" value="1"  onClick="Goahead (1);"><?php print $a[$randval2][1] ; ?>
                <br><input type="radio" name="option" value="2"  onClick="Goahead (2);"><?php print $a[$randval2][2] ; ?>
                <br><input type="radio" name="option" value="3"  onClick="Goahead (3);"><?php print $a[$randval2][3] ; ?>
                <br><input type="radio" name="option" value="4"  onClick="Goahead (4);"><?php print $a[$randval2][4] ; ?>
                <br><input style="font-family:Trebuchet ms; color:#f77779; font-size:15px; width:60px; border:1px;" type="text" name="response" size=8></div>
              </form>
              <div style="padding-left:-150px; margin-left:-300px; padding-right:10px;">
                <form id="show-form">
              <br><a href="#" class="link" onclick="showPenjelasanForm()">Show Explanation</a><br><br><hr>
              </form>

              <form id="hide-form" style="display:none">
              <br><a href="#" class="link" onclick="showListForm()">Hide Explanation</a><br><br><hr>
              </form>

              <form id="penjelasan-form" style="display:none">
              <br>
              <div class="text1"><?php print $a[$randval2][5] ; ?><br><br>
              </div>
              </form>
              </div>
              <?php
              }else{
              ?>
              <tr><td align="center">
              The Quiz has finished<br>
              <br>Percentage of correct answer: <?php print $percentaje ; ?> %
              <p><a href="<?php print $address; ?>">Restart</a>

              <?php } ?>

              </td></tr>
              
            </table>

          </div>
        </div>
    </div>
  </div>
  </div>
</div>
<!-- End Grammar -->

<footer>
      <div class="copy2"></a> &copy; Febriani F Damanik (132406106) | <a href="#">Privacy Policy</a> <br> </div>
</footer>
</body>
</html>